### ISSUE TITLE
Decimal, Binario, Octal y Hexadecimal Ahora con int

### ISSUE THREAD

**Issue by LucasVizcaino** [CodeSystem2022/Team-Fortran-Cuarto-Semestre-2023#9]
- [x] Decimal, Binario, Octal y Hexadecimal #8
- [x] Decimal, Binario, Octal y Hexadecimal Ahora con int #9

**Comment by danisa-morales** [comment]
Se realiza el issue #9 y el issue #8 (unido a la rama previamente, sin contenido)
